### PR TITLE
Updated outline

### PR DESCRIPTION
**Pull request by jenineharris**

### CODE REVIEW

**Comment by dgkeyes** [comment]
Thanks @jenineharris! This looks great overall. 

A few points of feedback:

- It seems like lesson 8 on functions should come before lesson 5 on function arguments. Explaining the general concept of functions before discussing details look argument position makes sense to me. Thoughts?

- On lesson 9 on RMarkdown, I would approach it as follows: just give a broad overview of what RMarkdown is. I cover it in-depth in my Fundamentals and Going Deeper courses so we can point people there if they need an intro to it. I'm ok to keep the sections you have laid out, but let's just have you keep this lesson short.

- On lesson 10, can you explain how the data embedding with the `xfun` package works? I've never seen that and don't quite get it.

Please feel free to update the outline and then we can look at merging your PR.

**Comment by jenineharris** [comment]
> Thanks @jenineharris! This looks great overall.
> 
> A few points of feedback:
> 
> * It seems like lesson 8 on functions should come before lesson 5 on function arguments. Explaining the general concept of functions before discussing details look argument position makes sense to me. Thoughts?

I'd say that function arguments would come first because they are used in all functions (e.g., ggplot() has a lot of arguments like x = , y = , color = , fill = ). Creating your own function seems a little more advanced and knowing how to use function arguments generally will help students write clearer functions. Does that sound ok?

> * On lesson 9 on RMarkdown, I would approach it as follows: just give a broad overview of what RMarkdown is. I cover it in-depth in my Fundamentals and Going Deeper courses so we can point people there if they need an intro to it. I'm ok to keep the sections you have laid out, but let's just have you keep this lesson short.

Sounds great!

> * On lesson 10, can you explain how the data embedding with the `xfun` package works? I've never seen that and don't quite get it.

The package puts a little link in the upper right corner of html output that links to the RMarkdown and data files (or any file you want to embed). It only works with html files. Here is a short description: https://yihui.org/en/2018/07/embed-file/

It's only available for embedding files < 2 MB in html documents. If this seems too narrow for the course, that's completely fine. 

> 
> Please feel free to update the outline and then we can look at merging your PR.

**Comment by dgkeyes** [comment]
> I'd say that function arguments would come first because they are used in all functions (e.g., ggplot() has a lot of arguments like x = , y = , color = , fill = ). Creating your own function seems a little more advanced and knowing how to use function arguments generally will help students write clearer functions. Does that sound ok?

That sounds good to me! Let's just make sure that you make clear you're talking about argument order in functions made by others.

**Comment by dgkeyes** [comment]
I'm going to go ahead and merge this, thanks!

**Pull request merged**
